# Generated by Django 4.1.3 on 2022-11-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_rename_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
