# Generated by Django 4.1.3 on 2022-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
