# Generated by Django 4.1.3 on 2022-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0009_alter_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
