# Generated by Django 4.1.3 on 2022-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0010_alter_customuser_phone_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
