# Generated by Django 4.1.3 on 2022-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0011_shippingaddress_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
