# Generated by Django 4.1.3 on 2022-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0013_alter_shippingaddress_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='company_name',
            new_name='appartment_no',
        ),
    ]
