# Generated by Django 4.1.3 on 2022-11-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0017_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
