# Generated by Django 4.1.3 on 2022-11-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0018_orderstatus_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_home.orderstatus'),
        ),
    ]
