# Generated by Django 4.1.3 on 2022-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0026_extraimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='strap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
