# Generated by Django 4.1.3 on 2022-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0030_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
