# Generated by Django 4.1.3 on 2022-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0033_alter_salesreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
