# Generated by Django 4.1.3 on 2022-12-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0036_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
