# Generated by Django 4.1.3 on 2022-12-05 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0038_shippingaddress_name_shippingaddress_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('discount', models.PositiveIntegerField()),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
