# Generated by Django 4.1.3 on 2022-12-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0040_coupon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
    ]
