# Generated by Django 4.1.3 on 2022-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0041_remove_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
