# Generated by Django 4.1.3 on 2022-12-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0045_remove_order_order_total_order_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
