# Generated by Django 4.1.3 on 2022-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0047_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
