# Generated by Django 4.1.3 on 2022-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0048_orderitem_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
