# Generated by Django 4.1.3 on 2022-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0051_product_offer_product_offer_price_productoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
