# Generated by Django 4.1.3 on 2022-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0052_alter_productoffer_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
