# Generated by Django 4.1.3 on 2022-12-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0054_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Order',
            new_name='order',
        ),
    ]
