# Generated by Django 4.1.3 on 2022-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0057_sale_cancel_item_sale_cancel_price_alter_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancel_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancel_item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
