# Generated by Django 4.1.3 on 2022-12-08 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0060_alter_customuser_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cancel_item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cancel_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cancel_quantity',
        ),
        migrations.CreateModel(
            name='CancelSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_home.order')),
            ],
        ),
    ]
