# Generated by Django 4.1.3 on 2022-12-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0061_remove_sale_cancel_item_remove_sale_cancel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelsale',
            name='quantity',
        ),
    ]
