# Generated by Django 4.1.3 on 2022-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0062_remove_cancelsale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelsale',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
