# Generated by Django 4.1.3 on 2022-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0066_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.BooleanField(default=False),
        ),
    ]
