# Generated by Django 4.1.3 on 2022-12-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0067_order_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
