# Generated by Django 4.1.3 on 2022-12-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0068_order_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.BooleanField(default=False),
        ),
    ]
