# Generated by Django 4.1.3 on 2022-12-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0072_remove_shippingaddress_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_home.category'),
        ),
    ]
