from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_home, name='user_home'),
    path('login', views.user_login, name='user_login'),
    path('user_otp', views.user_otp, name='user_otp'),
    path('otp_confirm', views.otp_confirm, name='otp_confirm'),
    path('register', views.user_register, name='user_register'),
    path('logout', views.user_logout, name='user_logout'),
    path('list/<int:id>', views.list, name='list'),
    path('list/details/<int:id>', views.details, name='details'),
    path('account', views.user_account, name='user_account'),
    path('user_account_update', views.user_account_update, name='user_account_update'),
    path('address_delete/<int:id>', views.address_delete, name='address_delete'),
    path('address_create', views.address_create, name='address_create'),
    path('order_details/<int:id>', views.order_details, name='order_details'),
    path('checkout', views.checkout, name='checkout'),
    path('cart', views.cart, name='cart'),
    path('cart_item_delete', views.cart_item_delete, name='cart_item_delete'),
    path('coupon_apply', views.coupon_apply, name='coupon_apply'),
    path('coupon_delete', views.coupon_delete, name='coupon_delete'),
    path('update_item', views.update_item, name='update_item'),
    path('list/update_item', views.update_item, name='list_update_item'),
    path('list/details/update_item', views.update_item, name='list_details_update_item'),
    path('update_item_guest', views.update_item_guest, name='update_item_guest'),
    path('list/update_item_guest', views.update_item_guest, name='list_update_item_guest'),
    path('list/details/update_item_guest', views.update_item_guest, name='list_details_update_item_guest'),
    path('delete_item_guest', views.delete_item_guest, name='cart_delete_item_guest'),
    path('order_address', views.order_address, name='order_address'),
    path('payment', views.payment, name='payment'),
    path('process_order', views.process_order, name='process_order'),
    path('order_complete', views.order_complete, name='order_complete'),
    path('order_delete/<int:id>', views.order_delete, name='order_delete'),
    path('orderItem_delete/<int:p_id>/<int:o_id>', views.orderItem_delete, name='orderItem_delete'),
    path('return_confirm', views.return_confirm, name='return_confirm'),
    path('redeem_wallet', views.redeem_wallet, name='redeem_wallet'),
    path('remove_wallet', views.remove_wallet, name='remove_wallet'),
    path('invoice/<int:id>', views.invoice, name='invoice'),
]